name: HealthCardControlKit
options:
  bundleIdPrefix: de.gematik.ti.healthcardcontrol
  deploymentTarget:
    macOS: 10.12
    iOS: 12.1
settings:
  base:
    SWIFT_VERSION: 5.0
    ALWAYS_SEARCH_USER_PATHS: NO
    FRAMEWORK_SEARCH_PATHS: "$(inherited)"
  configs:
    Release:
      SWIFT_COMPILATION_MODE: wholemodule
    Debug:
      SWIFT_COMPILATION_MODE: incremental
targets:
  HealthCardControlKit:
    type: framework
    platform: [iOS,macOS]
    info:
      path: Resources/HealthCardControlKit_Info.plist
    sources:
      - path: Sources/HealthCardControl
    dependencies:
      - target: BigIntExt_${platform}
      - carthage: HealthCardAccessKit
      - carthage: CardReaderProviderApi
      - carthage: CardReaderAccess
      - carthage: GemCommonsKit
      - carthage: ASN1Kit
      - carthage: DataKit
      - carthage: BigInt
    scheme:
      testTargets:
        - HealthCardControlKitTests_${platform}
      gatherCoverageData: true
  BigIntExt:
    type: framework
    platform: [iOS,macOS]
    info:
      path: Resources/BigIntExt_Info.plist
    sources:
      - Sources/BigIntExt
    dependencies:
      - carthage: BigInt
    scheme:
      testTargets:
        - BigIntExtTests_${platform}
      gatherCoverageData: true
  HealthCardControlKitTests:
    name: HealthCardControlKitTests_${platform}
    type: bundle.unit-test
    platform: [macOS,iOS]
    sources:
      - path: Tests
        excludes:
          - "HealthCardControlTests/Integration"
          - "HealthCardControlTests/Util/CardSimulatorTerminalResource.swift"
          - "HealthCardControlTests/Util/HCCTerminalTestCase.swift"
    dependencies:
    - target: HealthCardControlKit_${platform}
    - carthage: HealthCardAccessKit
    - carthage: CardReaderProviderApi
    - carthage: CardReaderAccess
    - carthage: Nimble
    - carthage: DataKit
    - carthage: BigInt
  BigIntExtTests:
    type: bundle.unit-test
    platform: [macOS,iOS]
    sources:
      - path: Tests/BigIntExtTests
    dependencies:
      - carthage: BigInt
buildImplicitDependencies: true
