name: HealthCardControlKit
options:
  bundleIdPrefix: de.gematik.ti.healthcardcontrol
  deploymentTarget:
    macOS: 10.12
    iOS: 12.1
settings:
  base:
    SWIFT_VERSION: 5.0
    ALWAYS_SEARCH_USER_PATHS: NO
    FRAMEWORK_SEARCH_PATHS: "$(inherited)"
  configs:
    Release:
      SWIFT_COMPILATION_MODE: wholemodule
    Debug:
      SWIFT_COMPILATION_MODE: incremental
targets:
  HealthCardControlKit:
    type: framework
    platform: [iOS,macOS]
    info:
      path: Resources/HealthCardControlKit_Info.plist
    sources:
      - path: Sources/HealthCardControl
    dependencies:
      - carthage: HealthCardAccessKit
        embed: true
      - carthage: GemCommonsKit
        embed: true
      - carthage: ASN1Kit
        embed: true
      - carthage: DataKit
        embed: true
      - carthage: BigInt
        embed: true
    transitivelyLinkDependencies: true
    scheme:
      testTargets:
        - HealthCardControlKitTests_${platform}
      gatherCoverageData: true
  HealthCardControlKitTests:
    name: HealthCardControlKitTests_${platform}
    type: bundle.unit-test
    platform: [macOS,iOS]
    info:
      path: Resources/HealthCardControlKitTests_Info.plist
    sources:
      - path: Tests/HealthCardControlTests
        excludes:
          - Integration
          - Common
          - Resources.bundle
    dependencies:
    - target: HealthCardControlKit_${platform}
    - carthage: CardReaderProviderApi
    - carthage: CardReaderAccess
    - carthage: Nimble
buildImplicitDependencies: true
